apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: lra-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
