apiVersion: apps/v1
kind: Deployment
metadata:
  name: alb-nginx
  namespace: lra-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alb-nginx
  template:
    metadata:
      labels:
        app: alb-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: tls-secret
              mountPath: /etc/nginx/tls
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: alb-nginx-config
        - name: tls-secret
          secret:
            secretName: alb-nginx-tls
