apiVersion: v1
kind: ConfigMap
metadata:
  name: alb-nginx-config
  namespace: lra-poc
data:
  default.conf: |
    # Redirect all HTTP to HTTPS
    server {
      listen 80;
      server_name _;

      return 301 https://$host$request_uri;
    }

    # HTTPS server
    server {
      listen 443 ssl;
      server_name _;

      ssl_certificate /etc/nginx/tls/tls.crt;
      ssl_certificate_key /etc/nginx/tls/tls.key;

      location / {
        proxy_pass http://frontend-service:80;
      }

      location /api/ {
        proxy_pass http://api-gateway-service:8080;
        rewrite ^/api(/.*)$ $1 break;
      }
    }
