apiVersion: apps/v1
kind: Deployment
metadata:
  name: alb-nginx
  namespace: lra-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alb-nginx
  template:
    metadata:
      labels:
        app: alb-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: alb-nginx-config
