apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: lra-poc
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'sandbox.smtp.mailtrap.io:2525'
      smtp_from: 'alert@carrillo.com'
      smtp_auth_username: '4ab84a792a9393'
      smtp_auth_password: 'b2f63ca56b44c5' 
      smtp_require_tls: true

    route:
      receiver: email-alerts
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 3m
      repeat_interval: 2m

    receivers:
      - name: email-alerts
        email_configs:
          - to: 'johnchristopher.carrillo@gmail.com'
            send_resolved: true
            require_tls: true
