apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: lra-poc
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'johnchristopher.carrillo@gmail.com'
      smtp_auth_username: 'johnchristopher.carrillo@gmail.com'
      smtp_auth_password: 'rifxfsxylhqpiywa'  # <- Gmail App Password
      smtp_require_tls: true

    route:
      receiver: email-alerts
      group_by: ['alertname']
      group_wait: 0s
      group_interval: 10s
      repeat_interval: 1m

    receivers:
      - name: email-alerts
        email_configs:
          - to: 'johnchristopher.carrillo@gmail.com'
            send_resolved: true
            require_tls: true
