apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-rules
  namespace: lra-poc
data:
  alert-rules.yaml: |
    groups:
      - name: k8s-alerts
        rules:
          - alert: HighCPUUsage
            expr: rate(process_cpu_seconds_total{job="api-gateway"}[1m]) > 0.005
            for: 30s
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage detected on API Gateway"
              description: "App-level CPU usage (from prom-client) is above threshold for more than 30 seconds on pod {{ $labels.pod }}."

          - alert: TooManyReplicas
            expr: count(up{job="api-gateway"}) > 3
            for: 30s
            labels:
              severity: warning
            annotations:
              summary: "Too many API Gateway pods running"
              description: "More than 3 'up' targets (active pods) of API Gateway are reporting to Prometheus."

          - alert: TooManyRequests
            expr: rate(http_requests_total{status="429", pod=~"api-gateway.*"}[1m]) > 1
            for: 30s
            labels:
              severity: critical
            annotations:
              summary: "Too many requests resulting in HTTP 429"
              description: "More than 1 HTTP 429 response per second from API Gateway in the last 1 minute."
