apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: lra-poc  # ✅ specify namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest  # ✅ replace with your Docker Hub image
          ports:
            - containerPort: 8081
          imagePullPolicy: Never
