apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: lra-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          ports:
            - containerPort: 8081
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "40m"
            limits:
              cpu: "200m"
