apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: lra-poc  # ✅ include this to place it in the correct namespace
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
