apiVersion: v1
kind: Service
metadata:
  name: lambda-producer-service
  namespace: lra-poc
spec:
  selector:
    app: lambda-producer
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
