apiVersion: v1
kind: Service
metadata:
  name: lambda-consumer-service
  namespace: lra-poc
spec:
  selector:
    app: lambda-consumer
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
