apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: lra-poc
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway.lra-poc.svc.cluster.local:8081']
