apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: lra-poc
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager.lra-poc.svc.cluster.local:9093']  # <- ito ang Alertmanager service name

    scrape_configs:
      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway.lra-poc.svc.cluster.local:8081']

    rule_files:
      - /etc/prometheus/rules/*.yaml
